package ru.aston.sort_app.core;

public enum UserInputChoice {
    MENU_MAIN,
    MENU_ADD_DATA,

    MENU_USER_GENERATED,
    ACTION_CAR_MANUAL_GENERATED,
    ACTION_BOOK_MANUAL_GENERATED,
    ACTION_ROOTCROP_MANUAL_GENERATED,

    MENU_RANDOM_GENERATION,
    ACTION_CAR_RANDOM_GENERATED,
    ACTION_BOOK_RANDOM_GENERATED,
    ACTION_ROOTCROP_RANDOM_GENERATED,

    MENU_FILE_GENERATED,
    ACTION_CAR_FILE_GENERATED,
    ACTION_BOOK_FILE_GENERATED,
    ACTION_ROOTCROP_FILE_GENERATED,

    MENU_SEARCH,
    ACTION_CAR_SEARCH,
    ACTION_BOOK_SEARCH,
    ACTION_ROOTCROP_SEARCH,

    MENU_SORT,
    ACTION_CAR_SORT,
    ACTION_BOOK_SORT,
    ACTION_ROOTCROP_SORT,

    ACTION_SAVE_DATA,
    EXIT

}
